version: '3.8'
services:
  website:
    container_name: 'CRM'
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./prisma/production.db:/app/prisma/db.db
    build:
      context: .
      dockerfile: Dockerfile
      target: app
